import { Poppins } from "next/font/google";
import "./globals.css";
import Logo from "~/components/ui/logo";
import Sidebar from "~/components/layout/sidebar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${poppins.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-main">
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
